update

diff --git a/_kakoune/.config/kak/kakrc b/_kakoune/.config/kak/kakrc
--- a/_kakoune/.config/kak/kakrc
+++ b/_kakoune/.config/kak/kakrc
@@ -1,20 +1,44 @@
 colorscheme cemant
+
 set-option global grepcmd 'rg --line-number --with-filename'
 set-option global indentwidth 2
-set-option global modelinefmt '{StatusLineInfo}%sh{expr >/dev/null "${#kak_bufname}" ">" `expr \`tput cols\` "/" 2` && printf "$kak_bufname" | sed "s_[^/]\+\$__" | sed "s_\([^/]\{,2\}\)[^/]*/_\1/_g" || printf "$kak_bufname" | sed "s_[^/]\+\$__"}{black,white}%sh{printf "$kak_bufname" | sed "s_^.*/__"}{StatusLineInfo}:%val{buf_line_count}/{black}%val{cursor_line}{StatusLineInfo}:{black}%val{cursor_char_column}{{context_info}} {{mode_info}}'
+set-option global modelinefmt '{StatusLineInfo}%sh{expr >/dev/null "${#kak_bufname}" ">" `expr \`tput cols\` "/" 2` && printf "${kak_bufname}" | sed "s_[^/]\+\$__" | sed "s_\([^/]\{,2\}\)[^/]*/_\1/_g" || printf "${kak_bufname}" | sed "s_[^/]\+\$__"}{black,white}%sh{printf "${kak_bufname}" | sed "s_^.*/__"}{StatusLineInfo}:%val{buf_line_count}/{black}%val{cursor_line}{StatusLineInfo}:{black}%val{cursor_char_column}{{context_info}} {{mode_info}}'
 set-option global tabstop 2
 set-option global ui_options terminal_assistant=none terminal_enable_mouse=yes terminal_set_title=yes terminal_status_on_top=yes
+
 add-highlighter global/ number-lines -hlcursor -separator ' '
 add-highlighter global/ regex \h+$ 0:Error
 add-highlighter global/ regex '(FIXME|NOTE|TODO|WIP|XXX)' 0:black,bright-blue+F
 add-highlighter global/ show-matching
 add-highlighter global/ wrap
+
 define-command -buffer-completion 0sh 'set-option buffer filetype sh' -docstring 'set filetype to sh'
 define-command -buffer-completion 0xml 'set-option buffer filetype xml' -docstring 'set filetype to xml'
 define-command -buffer-completion d 'delete-buffer' -docstring 'delete current buffer'
+
+hook global BufCreate .* %{ evaluate-commands %sh{
+  # recognise filetypes that snuck past detection/file.kak
+  if test -z "${kak_opt_filetype}"; then
+    case $(file -b --mime-type -L "${kak_buffile}") in
+      text/x-tcl) printf "set-option buffer filetype sh\n" ;; # no tcl atm
+    esac
+  fi
+} }
 hook global BufCreate .*\.tcl %{
   set-option buffer filetype sh
 }
+hook global BufWritePost .* %{
+  # backup files on write
+  evaluate-commands %sh{
+    bakd="${HOME}/bak/kak"
+    test -d "${bakd}" && test -w "${bakd}" \
+    || (printf "info %%{cannot write to backup directory\n${bakd}}" && exit)
+    bakf="${bakd}/"$(/usr/bin/basename "${kak_buffile}")"~"
+    /usr/bin/diff >/dev/null 2>&1 -q "${kak_buffile}" "${bakf}" && exit
+    /usr/bin/cp >/dev/null -f "${kak_buffile}" "${bakf}"
+  }
+}
+
 map global normal <C> ''
 map global normal <a-space> ''
 map global insert <c-v> ''
@@ -41,10 +65,16 @@ map global normal <c-p> '!wl-paste<space>--no-newline<ret>:echo -markup "{Inform
 map global normal <a-v>   <c-b>       -docstring 'scroll up page'
 map global normal <c-v>   <c-f>       -docstring 'scroll down page'
 map global normal <c-y> '<a-|>wl-copy<ret>:echo -markup "{Information}yanked to clipboard"<ret>' -docstring 'yank selection into clipboard'
-map global insert <a-d>   <esc>'Glxd'     -docstring 'delete extended line'
-map global insert <c-g>   <esc><space>   -docstring 'remove secondary selections'
-map global insert <a-g>   <esc><a-space> -docstring 'remove primary selection'
-map global insert <a-v>   <esc><c-b>     -docstring 'scroll up page'
-map global insert <c-q>   <c-v>          -docstring 'raw insert'
-map global insert <c-v>   <esc><c-f>     -docstring 'scroll down page'
+map global insert <a-d> <esc>'Glxd'    -docstring 'delete extended line'
+map global insert <c-g> <esc><space>   -docstring 'remove secondary selections'
+map global insert <a-g> <esc><a-space> -docstring 'remove primary selection'
+map global insert <a-v> <esc><c-b>     -docstring 'scroll up page'
+map global insert <c-q> <c-v>          -docstring 'raw insert'
+map global insert <c-v> <esc><c-f>     -docstring 'scroll down page'
+
+# rainbow.kak
+set-option global rainbow_colors black magenta blue bright-blue cyan green yellow bright-black
+hook global WinSetOption filetype=.+ %{
+  rainbow-enable-window
+}
 
